sonar.projectKey=cartwave-payments
sonar.projectName=Cartwave Payments API
sonar.projectVersion=1.0.0

# SonarCloud (obrigatório na nuvem): descomente ou use env SONAR_ORGANIZATION
# sonar.organization=your-organization-key

sonar.sources=src
sonar.tests=tests
sonar.language=js

sonar.exclusions=**/node_modules/**,**/coverage/**,**/src/infrastructure/database/migrations/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
